flask_project/app/models.py
""" Model """
from app import db
from app import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    """User Model"""
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    telephone = db.Column(db.String(11), unique=True, nullable=False)
    email = db.Column(db.String(64), unique=True)
    username = db.Column(db.String(50), nullable=False)
    password_hash = db.Column(db.String(128))

    #  role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    @property
    def password(self):
        raise AttributeError('password is not a readable attrribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


class Discuss(db.Model):
    """Discuss Model"""
    __tablename__ = 'discuss'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False)
    content = db.Column(db.Text(), nullable=False)

flask_project/app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo  # , Regexp
from wtforms import ValidationError


class EditBlogForm(FlaskForm):
    pass

flask_project/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo  # , Regexp
from wtforms import ValidationError

flask_project/app/__init__.py
""" app/__init__.py"""
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_cors import CORS
from flask_misaka import Misaka
from celery import Celery
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
migrate = Migrate()
misaka = Misaka()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name='default'):
    """ create app """
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    misaka.init_app(app)
    login_manager.init_app(app)
    CORS(app)
    # add router
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    from .email import email_bp as email_blueprint
    from .blog import blog as blog_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(email_blueprint)
    app.register_blueprint(blog_blueprint)
    return app


def create_celery_app(app=None):
    """ create celery app """
    app = app or create_app('default')
    celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
    celery.conf.update(app.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        """ Context Task """
        abstract = True

        def __call__(self, *args, **kwargs):
            with app.app_context():
                return super(TaskBase, self).__call__(*args, **kwargs)
    celery.Task = ContextTask
    return celery

flask_project/app/blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog', __name__, url_prefix='/blog')

from . import views

flask_project/app/blog/views.py
''' blog views '''
from flask import render_template
from flask_login import login_required
from . import blog

content = """
# README
## README
### README
"""


@blog.route('/')
@login_required
def index():
    """ blog index """
    return render_template('blog/index.html', text=content)


@blog.route('/edit/', methods=['GET', 'POST'])
@login_required
def edit():
    """ write blog """
    return render_template('blog/md.html')

flask_project/app/main/__init__.py
#app/main/__init__.py 创建主蓝本
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

flask_project/app/main/views.py
"""
main app '/'
"""
from flask import render_template, request, session, url_for, redirect
from flask_login import login_required
from . import main
from .. import db
from ..models import User, Discuss
#  from ..decorators import login_required


@main.route('/test_json')
def test():
    """ test url """
    return {'test': 'test_message'}


@main.route('/')
@login_required
def index():
    """index"""
    message = {'discuss': Discuss.query.order_by(Discuss.id)}
    return render_template('index.html', message=message)


@main.route('/login/', methods=['GET', 'POST'])
def login():
    """ login """
    if request.method == 'GET':
        return render_template('login.html')
    telephone = request.form.get('telephone')
    password = request.form.get('password')
    user = User.query.filter(User.telephone == telephone).first()
    if user and user.verify_password(password):
        session['user_id'] = user.id
        session.permanent = True
        return redirect(url_for('main.index'))

    return render_template('login.html',
                           message={'error: phone or password error!'})


@main.route('/register/', methods=['GET', 'POST'])
def register():
    """ register """
    if request.method == 'GET':
        return render_template('register.html')
    # POST
    telephone = request.form.get('telephone')
    username = request.form.get('username')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')
    user = User.query.filter(User.telephone == telephone).first()
    if user:
        return 'telephone exist! Please change.'
    if password1 != password2:
        return 'password confirm error!'
    user = User(
        telephone=telephone,
        username=username,
        password=password1)
    db.session.add(user)
    db.session.commit()
    return redirect(url_for('main.login'))


@main.route('/old_logout/')
def old_logout():
    """ old logout """
    session.pop('user_id')
    # del session['user_id']
    # session.clear()
    return redirect(url_for('auth.login'))


@main.route('/send_discuss/', methods=['GET', 'POST'])
@login_required
def send_question():
    """ send question """
    if request.method == 'GET':
        return render_template('send_discuss.html')
    # POST
    title = request.form.get('title')
    content = request.form.get('content')
    discuss = Discuss(title=title, content=content)
    db.session.add(discuss)
    db.session.commit()
    return redirect(url_for('main.index'))


@main.context_processor
def my_context_processor():
    """ my_context_processor """
    user_id = session.get('user_id')
    if user_id:
        user = User.query.filter(User.id == user_id).first()
        if user:
            return {'user': user}
    return {}

flask_project/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>{% block title %}{% endblock %}-WEB</title>

   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
         integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
         crossorigin="anonymous"> 
   <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
           integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
           crossorigin="anonymous"></script>
   {#    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
   {#    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>#}
   {#    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>#}
   {% block head %}{% endblock %}
   <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
</head>
<body class="body">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a dispaly="flex" class="navbar-brand" href="#">
              <img class='logo' src="{{ url_for('static', filename='images/logo.jpeg') }}" alt="">
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active">
                <a left="-15px" href="{{ url_for('main.index') }}">Index <span class="sr-only">(current)</span></a>
              </li>
              <li>
                  <a href="{{ url_for('main.send_question') }}">SendQuestion</a>
              </li>
              <li><a href="{{ url_for('blog.edit') }}"> Write </a></li>
              <li><a href="{{ url_for('blog.index') }}"> Blog </a></li>
              <li><a href="{{ url_for('email.index') }}">Mail</a></li>
          </ul>
            <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Enter Key">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
{#                <li><a href="https://github.com/QAlexBall"> Github </a></li>#}
                <li><a href="http://119.23.33.220:8088/ocr/"> AI </a></li>
                {% if current_user.is_authenticated %}
                  <li><a href="http://119.23.33.220:8889"> Jupyter </a></li>
                  <li><a href="{{ url_for('main.index') }}">{{ current_user.username }}</a></li>
                  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                  <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                  <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}

            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main">
    {% block main %}

    {% endblock %}
    </div>
</body>
</html>

flask_project/app/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block head %}{% endblock %}

{% block main %}
  {{ text|markdown }}
{% endblock %}

flask_project/app/templates/blog/md.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='editormd/css/editormd.css') }}">
  <style>

  </style>
{% endblock %}

{% block main %}
  <h3 style="color: #00aaaa;font-family: 'Apple Braille',serif" class="page-title"> title
    <label>
      <input placeholder=""/>
    </label>
  </h3>
  <div id="test-editor">
    <label>
      <textarea style="display:none;"></textarea>
    </label>
  </div>
  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
  <script src="{{ url_for('static', filename='editormd/editormd.min.js') }}"></script>
  <script type="text/javascript">
    $(function() {
      const editor = editormd("test-editor", {
        width: "90%",
        height: 800,
        path: "{{ url_for('static', filename='editormd/lib/') }}"
      });
    })
  </script>
{% endblock %}

flask_project/app/templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block head %}{% endblock %}

{% block main %}

{% if message %}
  {% for dis in message.discuss %}
    <li> 
       {{ dis.title }} => <a> {{ dis.content }}</a>
    </li>

  {% endfor %}
{% else %}
This is Index Page!
{% endif %}

{% endblock %}

flask_project/app/templates/login.html
<!-- main login -->
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login_register.css') }}">
{% endblock %}

{% block main %}
    {% if message %}
      <p> {{ message }} </p>
    {% endif %}
    <h3 class="page-title">Login</h3>
    <form action="", method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="phone number" name="telephone">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="password" name="password">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">Login</button>
            </div>
        </div>
{% endblock %}

flask_project/app/templates/register.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}
Register
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login_register.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">Register</h3>
    <form action="", method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="phone number" name="telephone">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="username" name="username">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="password" name="password1">
            </div>

            <div class="form-group">
                <input type="password" class="form-control" placeholder="confirm password" name="password2">
            </div>

            <div class="form-group">
                <button class="btn btn-primary btn-block">Register</button>
            </div>
        </div>
    </form>
{% endblock %}

flask_project/app/templates/send_discuss.html
{% extends 'base.html' %}

{% block title %}
    send question
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/question.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title"> SendQuestion </h3>
    <form action="" method="post">
    <div class="form-container">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="please enter title" name="title">
        </div>
        <div class="form-group">
            <textarea name="content" class="form-control" rows="10"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-primary"> SUBMIT </button>
        </div>
    </div>
    </form>
{% endblock %}

flask_project/app/templates/send_question.html
{% extends 'base.html' %}

{% block title %}
    send question
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/question.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title"> SendQuestion </h3>
    <form action="" method="post">
    <div class="form-container">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="please enter title" name="title">
        </div>
        <div class="form-group">
            <textarea name="content" class="form-control" rows="10"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-primary"> SUBMIT </button>
        </div>
    </div>
    </form>
{% endblock %}

flask_project/app/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</body>
</html>